PPOlunarlander1:
  env_id: LunarLander-v3
  env_make_params:
    continuous: False
    gravity: -10.0
    enable_wind: False
    wind_power: 10.0
    turbulence_power: 1.5
  learning_rate: 0.0003
  gamma: 0.99
  hidden_dim: 128
  stop_on_reward: 200
  gae_lambda: 0.95
  clip_ratio: 0.2
  n_steps: 2048 # env steps per update
  n_epochs: 10 # passes per rollout
  minibatch_size: 64
  value_coef: 0.5
  entropy_coef: 0.01
  max_grad_norm: 0.5
